name: Build and Push Docker Image

on: [push]

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install pymupdf
          pip install pillow
          pip install opencv-python-headless
          pip install numpy
          pip install argparse

      - name: Build executable
        run: pyinstaller --onefile process_labels.py

      - name: Move executable to dist folder
        run: mv dist/process_labels dist/process_labels.elf

      - name: Compress ELF file (optional, adjust level if needed)
        run: gzip -9 dist/process_labels.elf

      - name: Add compressed file (or original if not compressed)
        run: |
          if [[ -f "dist/process_labels.elf.gz" ]]; then
            git add "dist/process_labels.elf.gz"
          else
            git add "dist/process_labels.elf"
          fi

      - name: Configure Git identity
        run: |
          git config user.name ${{ secrets.GIT_USER_NAME }}
          git config user.email ${{ secrets.GIT_USER_EMAIL }}

      - name: Commit changes
        run: git commit -m "Build and push ELF file (compressed if over 100MB)"

      - name: Push to repository
        run: git push origin main

      - name: Build Docker image
        run: |
          docker build -t your_dockerhub_username/your_image_name:tag .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push Docker image
        run: docker push your_dockerhub_username/your_image_name:tag        
