name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      output_path: "/tmp/label_print_job.pdf"
      dpi: 600
      error_margin_percent: 20
      set_margin: 0.1
      ant_threshold: 0.2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install pymupdf
        pip install pillow
        pip install opencv-python-headless
        pip install numpy
        pip install argparse

    - name: Build executable
      run: pyinstaller --onefile process_labels.py

    - name: Build Docker image
      run: |
        docker build -t gitkdf/cups-airprint-label-printer:latest .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push gitkdf/cups-airprint-label-printer:latest
