name: Build and Push Docker Image

on: [push]

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install pymupdf
          pip install pillow
          pip install opencv-python-headless
          pip install numpy
          pip install argparse

      - name: Build executable
        run: pyinstaller --onefile process_labels.py

      - name: Split the ELF file into 50MB chunks
        run: split -b 50m dist/process_labels dist/process_labels_split_part_

      - name: Add split parts to Git
        run: git add dist/process_labels_split_part_*

      - name: Check if there are changes to commit
        id: check_changes
        run: |
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Print no_changes value
        run: echo "no_changes=$no_changes"

      - name: Configure Git identity
        if: ${{ env.no_changes == 'false' }}
        run: |
          git config user.name ${{ secrets.GIT_user }}
          git config user.email ${{ secrets.GIT_USER_EMAIL }}

      - name: Commit changes
        if: env.no_changes == 'false'
        run: git commit -m "Build and push ELF file (split to 50MB)"

      - name: Push to repository
        if: env.no_changes == 'false'
        run: git push origin main

      - name: Build Docker image
        run: |
          docker build -t your_dockerhub_username/your_image_name:tag .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Push Docker image
        run: docker push your_dockerhub_username/your_image_name:tag        
